# BEGIN_KITTY_THEME
# Adapta Nokto Maia
include current-theme.conf
# END_KITTY_THEME

# Fuente
font_family      0xProto Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

# Ventana y Opacidad
background_opacity 0.90
window_padding_width 10

# Atajos útiles
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
